//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp17.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CheckEntities : DbContext
    {
        public CheckEntities()
            : base("name=CheckEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Муниципальные_образования> Муниципальные_образования { get; set; }
        public virtual DbSet<Образовательные_организации> Образовательные_организации { get; set; }
        public virtual DbSet<Приказы> Приказы { get; set; }
        public virtual DbSet<Присутствующие_при_проверке> Присутствующие_при_проверке { get; set; }
        public virtual DbSet<Проверка> Проверка { get; set; }
        public virtual DbSet<Специалисты> Специалисты { get; set; }
        public virtual DbSet<Формы_приказа> Формы_приказа { get; set; }
    }
}
