//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp17.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Образовательные_организации
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Образовательные_организации()
        {
            this.Проверка = new HashSet<Проверка>();
        }
    
        public int Код_образовательной_организации { get; set; }
        public string Наименование { get; set; }
        public string Сокращенное_наименование { get; set; }
        public string Адрес { get; set; }
        public int Код_муниципального_образования { get; set; }
    
        public virtual Муниципальные_образования Муниципальные_образования { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Проверка> Проверка { get; set; }
    }
}
