//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp17.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Приказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Приказы()
        {
            this.Проверка = new HashSet<Проверка>();
        }
    
        public int Код_приказа { get; set; }
        public string Номер_приказа { get; set; }
        public Nullable<System.DateTime> Дата_приказа { get; set; }
        public Nullable<int> Код_формы_приказа { get; set; }
    
        public virtual Формы_приказа Формы_приказа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Проверка> Проверка { get; set; }
    }
}
