//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp17.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Проверка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Проверка()
        {
            this.Присутствующие_при_проверке = new HashSet<Присутствующие_при_проверке>();
        }
    
        public int Код_проверки { get; set; }
        public Nullable<System.DateTime> Дата_проверки { get; set; }
        public Nullable<int> Код_образовательной_организации { get; set; }
        public Nullable<int> Код_специалиста { get; set; }
        public Nullable<int> Код_приказа { get; set; }
    
        public virtual Образовательные_организации Образовательные_организации { get; set; }
        public virtual Приказы Приказы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Присутствующие_при_проверке> Присутствующие_при_проверке { get; set; }
        public virtual Специалисты Специалисты { get; set; }
    }
}
